import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainContainer from "@/components/MainContainer";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-white text-gray-900 transition-colors  duration-300 dark:bg-gray-950 dark:text-gray-100">
        <AuthProvider>
          <ThemeProvider>
            <MainContainer>{children}</MainContainer>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
